FROM python:3.12.4-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

EXPOSE 8000

WORKDIR /apigateway

RUN apt-get update && apt-get install -y curl
RUN pip install --upgrade pip
RUN apt-get install -y --no-install-recommends postgresql-client

COPY . .

RUN pip install --no-cache-dir -r requirements.txt
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]

